FROM python:3.10.6
RUN pip install torch
RUN pip install fastapi 
RUN pip install uvicorn 
RUN pip install transformers
EXPOSE 80
COPY ./app ./app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0","--port", "8000"]